import type { Metadata } from 'next';
import { Rubik, Inter } from 'next/font/google';
import './globals.css';
import { SocketProvider } from '@/contexts/SocketContext';

export const rubik = Rubik({ subsets: ['latin'], variable: '--font-inter' });

export const inter = Inter({ subsets: ['latin'], variable: '--font-rubik' });

export const metadata: Metadata = {
  title: 'Talk to Me',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${rubik.variable} ${inter.variable}`}>
      <body className="bg-app-gray-950 text-app-white">
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
